"""Init

Revision ID: 1fa3200bfb0f
Revises: 
Create Date: 2019-09-02 23:13:50.418694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa3200bfb0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.VARCHAR(length=400), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('membertype', sa.Integer(), nullable=True),
    sa.Column('persontype', sa.Integer(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('company', sa.String(length=300), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('bday', sa.DateTime(), nullable=True),
    sa.Column('road', sa.String(length=400), nullable=True),
    sa.Column('town', sa.String(length=400), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=400), nullable=True),
    sa.Column('mobile', sa.VARCHAR(length=400), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bankdetails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_holder', sa.String(length=200), nullable=False),
    sa.Column('account_no', sa.Integer(), nullable=False),
    sa.Column('iban', sa.VARCHAR(length=500), nullable=False),
    sa.Column('iban_visible', sa.String(length=34), nullable=False),
    sa.Column('bic', sa.VARCHAR(length=400), nullable=False),
    sa.Column('bic_visible', sa.String(length=34), nullable=False),
    sa.Column('sepa_accepted', sa.Boolean(), nullable=True),
    sa.Column('sepa_date', sa.DateTime(), nullable=True),
    sa.Column('sepa_ref', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confirmation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('confirmation_code', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_code')
    )
    op.create_table('forgotpassword',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forgot_code', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forgot_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forgotpassword')
    op.drop_table('confirmation')
    op.drop_table('bankdetails')
    op.drop_table('user')
    # ### end Alembic commands ###
