"""empty message

Revision ID: 2c9118541995
Revises: 88dd782ecb37
Create Date: 2018-01-12 22:15:47.871913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c9118541995'
down_revision = '88dd782ecb37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'road')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('road', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
