"""empty message

Revision ID: 2fc4f5a0d798
Revises: 1c8b7137a9cd
Create Date: 2018-01-12 22:42:50.903795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc4f5a0d798'
down_revision = '1c8b7137a9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', sa.VARCHAR(length=400), nullable=False))
    op.add_column('user', sa.Column('phone', sa.VARCHAR(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'mobile')
    # ### end Alembic commands ###
