"""empty message

Revision ID: 4bd6cd33eb93
Revises: 
Create Date: 2018-01-10 22:15:01.074931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd6cd33eb93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=400), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('membertype', sa.Integer(), nullable=True),
    sa.Column('persontype', sa.Integer(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=300), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('bday', sa.DateTime(), nullable=True),
    sa.Column('road', sa.String(length=500), nullable=True),
    sa.Column('town', sa.String(length=400), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('mobile', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bankdetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_holder', sa.String(length=200), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('blz', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bic', sa.String(length=15), nullable=True),
    sa.Column('sepa_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('iban')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bankdetails')
    op.drop_table('user')
    # ### end Alembic commands ###
