"""empty message

Revision ID: 5b44bf1e15f0
Revises: 125c1197cb1a
Create Date: 2018-01-10 23:10:25.930164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b44bf1e15f0'
down_revision = '125c1197cb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_fee', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_fee')
    # ### end Alembic commands ###
