"""empty message

Revision ID: 5cc3ed8bc145
Revises: 2fc4f5a0d798
Create Date: 2018-01-12 22:49:50.126640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cc3ed8bc145'
down_revision = '2fc4f5a0d798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('iban', table_name='bankdetails')
    op.drop_column('bankdetails', 'iban')
    op.drop_column('bankdetails', 'bic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankdetails', sa.Column('bic', mysql.VARCHAR(length=15), nullable=False))
    op.add_column('bankdetails', sa.Column('iban', mysql.VARCHAR(length=34), nullable=False))
    op.create_index('iban', 'bankdetails', ['iban'], unique=True)
    # ### end Alembic commands ###
