"""empty message

Revision ID: 6c9b5df74f75
Revises: cdc9c95206a9
Create Date: 2018-01-11 20:40:00.537469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c9b5df74f75'
down_revision = 'cdc9c95206a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankdetails', sa.Column('sepa_accepted', sa.Boolean(), nullable=True))
    op.drop_column('bankdetails', 'blz')
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('monthlyfee', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'fee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fee', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'monthlyfee')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'admin')
    op.add_column('bankdetails', sa.Column('blz', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('bankdetails', 'sepa_accepted')
    # ### end Alembic commands ###
