"""empty message

Revision ID: 8409a37ccc0e
Revises: af1cc16ffe38
Create Date: 2018-01-13 00:33:36.596123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8409a37ccc0e'
down_revision = 'af1cc16ffe38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mobile',
               existing_type=mysql.VARCHAR(length=400),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mobile',
               existing_type=mysql.VARCHAR(length=400),
               nullable=False)
    # ### end Alembic commands ###
