"""empty message

Revision ID: 88dd782ecb37
Revises: 6c9b5df74f75
Create Date: 2018-01-12 21:17:58.142317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88dd782ecb37'
down_revision = '6c9b5df74f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forgotpassword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forgot_code', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forgot_code')
    )
    op.add_column(u'user', sa.Column('fee', sa.Integer(), nullable=False))
    op.add_column(u'user', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.drop_column(u'user', 'first_fee')
    op.drop_column(u'user', 'monthlyfee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('monthlyfee', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column(u'user', sa.Column('first_fee', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column(u'user', 'image_url')
    op.drop_column(u'user', 'fee')
    op.drop_table('forgotpassword')
    # ### end Alembic commands ###
