"""empty message

Revision ID: 972d83ac636e
Revises: 5cc3ed8bc145
Create Date: 2018-01-12 22:50:04.236349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972d83ac636e'
down_revision = '5cc3ed8bc145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankdetails', sa.Column('bic', sa.VARCHAR(length=400), nullable=False))
    op.add_column('bankdetails', sa.Column('iban', sa.VARCHAR(length=500), nullable=False))
    op.create_unique_constraint(None, 'bankdetails', ['iban'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bankdetails', type_='unique')
    op.drop_column('bankdetails', 'iban')
    op.drop_column('bankdetails', 'bic')
    # ### end Alembic commands ###
