"""empty message

Revision ID: ace73d953f89
Revises: e41f26d5a9ca
Create Date: 2018-01-13 18:03:05.437956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace73d953f89'
down_revision = 'e41f26d5a9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankdetails', sa.Column('iban', sa.VARCHAR(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bankdetails', 'iban')
    # ### end Alembic commands ###
