"""empty message

Revision ID: be3bd10d6176
Revises: e46789123e30
Create Date: 2018-01-11 00:51:47.908056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3bd10d6176'
down_revision = 'e46789123e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankdetails', sa.Column('sepa_ref', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bankdetails', 'sepa_ref')
    # ### end Alembic commands ###
