"""empty message

Revision ID: cdc9c95206a9
Revises: be3bd10d6176
Create Date: 2018-01-11 19:37:17.978769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc9c95206a9'
down_revision = 'be3bd10d6176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmation_code', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_code')
    )
    op.add_column('bankdetails', sa.Column('account_no', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    op.drop_column('bankdetails', 'account_no')
    op.drop_table('confirmation')
    # ### end Alembic commands ###
