"""empty message

Revision ID: daf8a3e5fd82
Revises: 5b44bf1e15f0
Create Date: 2018-01-11 00:00:38.047977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf8a3e5fd82'
down_revision = '5b44bf1e15f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankdetails', sa.Column('bic_visible', sa.String(length=34), nullable=False))
    op.add_column('bankdetails', sa.Column('iban_visible', sa.String(length=34), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bankdetails', 'iban_visible')
    op.drop_column('bankdetails', 'bic_visible')
    # ### end Alembic commands ###
