"""empty message

Revision ID: e1556432ef8c
Revises: 
Create Date: 2018-01-10 20:00:58.883430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1556432ef8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bankdetails')
    op.drop_table('migrate_version')
    op.drop_table('subscription')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=254), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('bday', mysql.DATETIME(), nullable=True),
    sa.Column('road', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('town', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('postcode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('phone', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mobile', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('subscription',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fee', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('migrate_version',
    sa.Column('repository_id', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', mysql.TEXT(), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('bankdetails',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('account_holder', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('account_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('blz', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('iban', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bic', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'bankdetails_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
