"""empty message

Revision ID: e41f26d5a9ca
Revises: f3de4bf4ddc7
Create Date: 2018-01-13 18:02:56.089666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e41f26d5a9ca'
down_revision = 'f3de4bf4ddc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankdetails', sa.Column('account_holder', sa.String(length=200), nullable=False))
    op.drop_column('bankdetails', 'iban')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankdetails', sa.Column('iban', mysql.VARCHAR(length=500), nullable=False))
    op.drop_column('bankdetails', 'account_holder')
    # ### end Alembic commands ###
