"""empty message

Revision ID: e46789123e30
Revises: daf8a3e5fd82
Create Date: 2018-01-11 00:05:49.499793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e46789123e30'
down_revision = 'daf8a3e5fd82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bankdetails', 'bic',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.alter_column('bankdetails', 'iban',
               existing_type=mysql.VARCHAR(length=34),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bankdetails', 'iban',
               existing_type=mysql.VARCHAR(length=34),
               nullable=True)
    op.alter_column('bankdetails', 'bic',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###
