"""empty message

Revision ID: f3de4bf4ddc7
Revises: ffb7dde8e076
Create Date: 2018-01-13 18:02:32.516068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3de4bf4ddc7'
down_revision = 'ffb7dde8e076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bankdetails', 'account_holder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankdetails', sa.Column('account_holder', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
