"""empty message

Revision ID: ffb7dde8e076
Revises: 8409a37ccc0e
Create Date: 2018-01-13 17:59:08.747947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb7dde8e076'
down_revision = '8409a37ccc0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('iban', table_name='bankdetails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('iban', 'bankdetails', ['iban'], unique=True)
    # ### end Alembic commands ###
